### PR TITLE
Replace "requests.delete" in "data_remover.py" with the "perform_request" function from "utils.py"

### PR DESCRIPTION
**Pull request by valyo**
Before submitting a PR to the `dev` branch:
- [x] Tests passing
- [x] Black formatting
- [x] Rebase/merge the `dev` branch

Additional checks before submitting a PR to the `master` branch:
- Change version in `dds_cli/version.py` (?)

### CODE REVIEW

**Comment by valyo** [comment]
I messed up the branches and got changes in account_manager.py here; not sure what is the best solution

**Comment by inaod568** [comment]
> I messed up the branches and got changes in account_manager.py here; not sure what is the best solution

No worries, it should be sorted out now!

**Comment by inaod568** [comment]
Actually, no, now apparently something else got messed up. I'll revert my merge and then we'll have a look @valyo

**Comment by valyo** [comment]
> 

ok, thanks

**Comment by inaod568** [comment]
> > 
> 
> ok, thanks

@valyo I've had a look now and it looks like the changes you made in this PR were also in the PR I merged recently, so there actually aren't any changes here, just as git is saying. So, no issues here! 👍🏻 Closing this since there are no changes. Have a look and let me know if you disagree and I've missed something. But it seems like what we have left now are a few post requests.

**Pull request closed without merging**
