### PR TITLE
Return exit code 1 if only partial upload

### PR DESCRIPTION
**Pull request by i-oden**
## **1. This PR contains the following changes...**

NGI noticed that some files were not uploaded, but the DDS had not returned an error code 1, which meant that they were not aware of any error. This should fix that. 

## **2. The following additional changes are required for this to work**

_X_

## **3. The PR fixes the following GitHub issue / Jira task**

- [ ] GitHub issue (link):
- [x] Jira task (ID, `DDS-xxxx`): DDS-1484
- [ ] The PR does not fix a specific GitHub issue or Jira task

## **4. What _type of change(s)_ does the PR contain?**

- [ ] New feature
  - [ ] Breaking: _Please describe the reason for the break and how we can fix it._
  - [ ] Non-breaking
- [x] Bug fix
  - [ ] Breaking: _Please describe the reason for the break and how we can fix it._
  - [x] Non-breaking
- [ ] Security Alert fix
- [ ] Documentation
- [ ] Tests **(only)**
- [ ] Workflow

### **Always**

- [Changelog](../CHANGELOG.md)
  - [x] Added
  - [ ] Not needed (E.g. PR contains _only_ tests)
- Rebase / Update / Merge _from_ base branch (the branch from which the current is forked)
  - [ ] Done
  - [x] Not needed
- Blocking PRs
  - [ ] Merged
  - [x] No blocking PRs
- PR to `master` branch
  - [ ] Yes: Go to the section [PR to master](#pr-to-master)
  - [x] No

### If PR consists of **code change(s)**

- Self review
  - [x] Done
- Comments, docstrings, etc
  - [x] Added / Updated
- Documentation
  - [ ] Updated
  - [x] Update not needed

## **6. Actions / Scans**

- **Black**: Python code formatter. Does not execute. Only tests.
  Run `black .` locally to execute formatting.
  - [x] Passed
- **Prettier**: General code formatter. Our use case: MD and yaml mainly.
  Run `npx prettier --write .` locally to execute formatting.
  - [x] Passed
- **Yamllint**: Linting of yaml files.
  - [x] Passed
- **Tests**: Pytest to verify that functionality works as expected.
  - [ ] New tests added
  - [x] No new tests
  - [x] Passed
- **TestPyPi**: Build CLI and publish to TestPyPi in order to verify before release.
  - [x] Passed
- **CodeQL**: Scan for security vulnerabilities, bugs, errors
  - [ ] New alerts: _Go through them and either fix, dismiss och ignore. Add reasoning in items below._
  - [ ] Alerts fixed: _What?_
  - [ ] Alerts ignored / dismissed: _Why?_
  - [x] Passed
- **Trivy**: Security scanner
  - [ ] New alerts: _Go through them and either fix, dismiss och ignore. Add reasoning in items below._
  - [ ] Alerts fixed: _What?_
  - [ ] Alerts ignored / dismissed: _Why?_
  - [x] Passed
- **Snyk**: Security scanner
  - [ ] New alerts: _Go through them and either fix, dismiss och ignore. Add reasoning in items below._
  - [ ] Alerts fixed: _What?_
  - [ ] Alerts ignored / dismissed: _Why?_
  - [x] Passed

### CODE REVIEW

**Review by valyo — APPROVED** [review]
Looks fine, but not sure how it can be tested manually

**Comment by i-oden** [comment]
> Looks fine, but not sure how it can be tested manually

👍🏻 

**How to test manually:**

1. Partial uploads
    
    a) `dds data put --source [file / directory 1] --project [project ID]` 
    b) `echo $?` should return `0`
    c) `dds data put --source [file / directory 1] --source [file / directory 2] --project [project ID]` 
    d) `echo $?` should return `1`

2. True failed

    a) Change line 202 in base.py from `if true_failed:` to `if not true_failed:`
    b)     a) `dds data put --source [file / directory 3] --project [project ID]` 
    b) `echo $?` should return `1`

**Comment by valyo** [comment]
Followed the manual testing protocol and everything works as expected.

**Comment by i-oden** [comment]
> Followed the manual testing protocol and everything works as expected.

Great!

**Pull request merged**
