### PR TITLE
Removing Werkzeug from requirements-test

### PR DESCRIPTION
**Pull request by i-oden**
## Read this before submitting the PR

1. Always create a Draft PR first
2. Go through sections 1-5 below, fill them in and check all the boxes
3. Make sure that the branch is updated; if there's an "Update branch" button at the bottom of the PR, rebase or update branch.
4. When all boxes are checked, information is filled in, and the branch is updated: mark as Ready For Review and tag reviewers (top right)
5. Once there is a submitted review, implement the suggestions (if reasonable, otherwise discuss) and request an new review.

If there is a field which you are unsure about, enter the edit mode of this description or go to the [PR template](https://github.com/ScilifelabDataCentre/dds_cli/blob/dev/.github/pull_request_template.md); There are invisible comments providing descriptions which may be of help.

## 1. Description / Summary

Solves Werkzeug vulnerability alerted via scans. 

## 2. Jira task / GitHub issue

https://scilifelab.atlassian.net/jira/software/projects/DDS/boards/13/backlog?epics=visible&selectedIssue=DDS-2040

## 3. Type of change

What _type of change(s)_ does the PR contain?

**Check the relevant boxes below. For an explanation of the different sections, enter edit mode of this PR description template.**

- [ ] New feature
  - [ ] Breaking: _Why / How? Add info here._ 
  - [ ] Non-breaking 
- [ ] Bug fix 
- [x] Security Alert fix 
  - [x] Package update 
    - [ ] Major version update 
- [ ] Documentation 
- [ ] Workflow 
- [ ] Tests **only** 

## 4. Additional information

- [ ] [Sprintlog](https://github.com/ScilifelabDataCentre/dds_cli/blob/dev/SPRINTLOG.md)  **Not adding sprintlog row since this only relates to tests.**
- [ ] Blocking PRs 
  - [ ] Merged 
- [ ] PR to `master` branch: _If checked, read [the release instructions](https://github.com/ScilifelabDataCentre/dds_cli/blob/dev/docs/procedures/new_release.md)_ 
  - [ ] I have followed steps 1-8. 

## 5. Actions / Scans

_Check the boxes when the specified checks have passed._

**For information on what the different checks do and how to fix it if they're failing, enter edit mode of this description or go to the [PR template](https://github.com/ScilifelabDataCentre/dds_cli/blob/dev/.github/pull_request_template.md).**

- [x] **Black**

- [x] **Pylint**

- [x] **Prettier**

- [x] **Yamllint**

- [x] **Tests**

- [x] **TestPyPI**

- [x] **CodeQL**

- [x] **Trivy**

- [x] **Snyk**

### CODE REVIEW

**Comment by rv0lt** [comment]
Why is it Werzeug needed in the tests in the client?

**Comment by i-oden** [comment]
> Why is it Werzeug needed in the tests in the client?

I was asking myself the same thing. At some point I'm pretty sure we needed it because some package had it as a requirement but didn't install it itself, but now I'm not sure. Currently testing if it's needed.

**Comment by i-oden** [comment]
@rv0lt Seems like it's no longer needed. Updating the title of this PR

**Review by rv0lt — APPROVED** [review]
Runned the tests and seem to work!

**Pull request merged**
