### PR TITLE
Update MacOs actions image due to broken pipeline

### PR DESCRIPTION
**Pull request by rv0lt**
## Read this before submitting the PR

1. Always create a Draft PR first
2. Go through sections 1-5 below, fill them in and check all the boxes
3. Make sure that the branch is updated; if there's an "Update branch" button at the bottom of the PR, rebase or update branch.
4. When all boxes are checked, information is filled in, and the branch is updated: mark as Ready For Review and tag reviewers (top right)
5. Once there is a submitted review, implement the suggestions (if reasonable, otherwise discuss) and request an new review.

If there is a field which you are unsure about, enter the edit mode of this description or go to the [PR template](https://github.com/ScilifelabDataCentre/dds_cli/blob/dev/.github/pull_request_template.md); There are invisible comments providing descriptions which may be of help.

## 1. Description / Summary

Fix broken changes in actions due to updtae in architecutre for underliying image

## 3. Type of change

What _type of change(s)_ does the PR contain?

**Check the relevant boxes below. For an explanation of the different sections, enter edit mode of this PR description template.**

- [ ] New feature
  - [ ] Breaking: _Why / How? Add info here._ 
  - [ ] Non-breaking 
- [ ] Bug fix 
- [ ] Security Alert fix 
  - [ ] Package update 
    - [ ] Major version update 
- [ ] Documentation 
- [x] Workflow 
- [ ] Tests **only** 

## 4. Additional information

- [x] [Sprintlog](https://github.com/ScilifelabDataCentre/dds_cli/blob/dev/SPRINTLOG.md) 
- [ ] Blocking PRs 
  - [ ] Merged 
- [ ] PR to `master` branch: _If checked, read [the release instructions](https://github.com/ScilifelabDataCentre/dds_cli/blob/dev/docs/procedures/new_release.md)_ 
  - [ ] I have followed steps 1-8. 

## 5. Actions / Scans

_Check the boxes when the specified checks have passed._

**For information on what the different checks do and how to fix it if they're failing, enter edit mode of this description or go to the [PR template](https://github.com/ScilifelabDataCentre/dds_cli/blob/dev/.github/pull_request_template.md).**

- [x] **Black**

- [x] **Pylint**

- [x] **Prettier**

- [x] **Yamllint**

- [x] **Tests**

- [x] **TestPyPI**

- [x] **CodeQL**

- [x] **Trivy**

- [x] **Snyk**

### CODE REVIEW

**Comment by rv0lt** [comment]
For reference: Change motivated by the issue explained in https://github.com/actions/runner-images/issues/9741#issuecomment-2075569220

Where the architecture for the default MacOs image is arm instead of Intel.

**Review by valyo — APPROVED** [review]
Aren't we adding a build for `macos-latest`, or will this one work on MacOS 14 too

**Comment by rv0lt** [comment]
> Aren't we adding a build for `macos-latest`, or will this one work on MacOS 14 too

As I understand, it won't work for AMD based Mac's. I.e, the new M1 and M2, for example, as they don't use intel chips anymore

**Comment by valyo** [comment]
Yes, but we should definitely have binaries for the arm arch MacOS. Maybe we should go for x86 now since we are running out of time. 
What is this "The base branch requires all commits to be signed" business about?

**Comment by rv0lt** [comment]
> Yes, but we should definitely have binaries for the arm arch MacOS. Maybe we should go for x86 now since we are running out of time. What is this "The base branch requires all commits to be signed" business about?

Yes, I was thinking we need some task to rethink this actions bussiness as they are giving more trouble than they should.

My fault, I don't know how but my GPG got deleted after updating the laptop. Now it is rebased

**Pull request merged**
