### PR TITLE
Allow upload to specific destination (directory)

### PR DESCRIPTION
**Pull request by inaod568**
> **Before submitting the PR, please go through the sections below and fill in what you can. If there are any items that are irrelevant for the current PR, remove the row. If a relevant option is missing, please add it as an item and add a PR comment informing that the new option should be included into this template.**

> **All _relevant_ items should be ticked before the PR is merged**

# Description

When downloading there's a `--destination` option which downloads the data to a specific local directory. So far there is no equivalent option for upload.

This PR adds this `--destination` option for `dds data put` and allows the user to upload data to a new or existing directory. 

- [x] Add a summary of the changes and the related issue
- [x] Add motivation and context regarding why the change is needed
- [x] Fixes DDS-1179

## Type of change

- [x] New feature (non-breaking)

# Checklist:

## General

- [x] [Changelog](../CHANGELOG.md): New row added. Not needed when PR includes _only_ tests.
- [x] Code change
  - [x] Self-review of code done
  - [x] Comments added, particularly in hard-to-understand areas
  - [x] Documentation is updated
    - [x] CLI - _Automatic_
    - [ ] Technical overview 

## Repository / Releases

- [x] Rebase / update of branch done

## Checks

- [x] Formatting: Black & Prettier checks pass
- [x] CodeQL passes
- [x] Tests
  - [x] I have added tests for the new code
  - [x] The tests pass

### CODE REVIEW

**Review by valyo — APPROVED** [review]
Works as expected and looks good

**Comment by inaod568** [comment]
> Works as expected and looks good

Great! Any suggestions for how to test this.... ?

**Comment by valyo** [comment]
> Great! Any suggestions for how to test this.... ?

not right out of my head, a least

**Comment by inaod568** [comment]
Test added.

**Pull request merged**
