### PR TITLE
Bump versions for rich and click to support rich-click

### PR DESCRIPTION
**Pull request by MatthiasZepper**
Before submitting a pr:
- [ ] Tests passing
- [ ] Black formatting
- [ ] Rebase/merge the `dev` branch
- [ ] Note in the CHANGELOG

### CODE REVIEW

**Review by talavis — COMMENTED** [review]
I think it’s better with a pip freeze to avoid any using like this

**Comment by MatthiasZepper** [comment]
> I think it’s better with a pip freeze to avoid any issues like this

Fair enough. I, however, have a lot more stuff in my conda virtual environment for some reason, so if I would do the freeze a lot unused stuff would end up there.

**Comment by inaod568** [comment]
Already changed the requirements file, lets check if that works now first.

**Comment by inaod568** [comment]
Meant to set this as a draft, not close.

**Comment by ewels** [comment]
Should no longer be required with rich-click v1.1.1 (though of course doesn't hurt).

**Comment by MatthiasZepper** [comment]
No longer relevant thanks to updates to the `rich-click` package. Thanks Phil!

**Pull request closed without merging**
