### PR TITLE
Version 2.5.1 and changelog

### PR DESCRIPTION
**Pull request by i-oden**
## Read this before submitting the PR

1. Always create a Draft PR first
2. Go through sections 1-5 below, fill them in and check all the boxes
3. Make sure that the branch is updated; if there's an "Update branch" button at the bottom of the PR, rebase or update branch.
4. When all boxes are checked, information is filled in, and the branch is updated: mark as Ready For Review and tag reviewers (top right)
5. Once there is a submitted review, implement the suggestions (if reasonable, otherwise discuss) and request an new review.

If there is a field which you are unsure about, enter the edit mode of this description or go to the [PR template](../.github/pull_request_template.md); There are invisible comments providing descriptions which may be of help.

## 1. Description / Summary

Change version to 2.5.1 and update changelog.

## 2. Jira task / GitHub issue

[DDS-1635](https://scilifelab.atlassian.net/jira/software/projects/DDS/boards/13?selectedIssue=DDS-1635)

## 3. Type of change

What _type of change(s)_ does the PR contain?

**Check the relevant boxes below. For an explanation of the different sections, enter edit mode of this PR description template.**

- [x] New feature
  - [ ] Breaking: _Why / How? Add info here._ 
  - [x] Non-breaking 
- [ ] Bug fix 
- [ ] Security Alert fix 
- [ ] Documentation 
- [x] Workflow 
- [ ] Tests **only** 

## 4. Additional information

- [x] [Sprintlog](../SPRINTLOG.md) 
- [ ] Blocking PRs 
  - [ ] Merged 
- [ ] PR to `master` branch: \_If checked, read [the release instructions](../doc/procedures/new_release.md) 
  - [ ] I have followed steps 1-8. 

## 5. Actions / Scans

- **Black**: Python code formatter. Does not execute. Only tests.
  Run `black .` locally to execute formatting.
  - [x] Passed
- **Pylint**: Python code linter. Does not execute. Only tests.
  Fix code producing warnings. Code must get 10/10.
  - [ ] Warnings fixed
  - [x] Passed
- **Prettier**: General code formatter. Our use case: MD and yaml mainly.
  Run `npx prettier --write .` locally to execute formatting.
  - [x] Passed
- **Yamllint**: Linting of yaml files.
  - [x] Passed
- **Tests**: Pytest to verify that functionality works as expected.
  - [ ] New tests added
  - [x] No new tests
  - [x] Passed
- **TestPyPi**: Build CLI and publish to TestPyPi in order to verify before release.
  - [x] Passed
- **CodeQL**: Scan for security vulnerabilities, bugs, errors
  - [ ] New alerts: _Go through them and either fix, dismiss och ignore. Add reasoning in items below._
  - [ ] Alerts fixed: _What?_
  - [ ] Alerts ignored / dismissed: _Why?_
  - [x] Passed
- **Trivy**: Security scanner
  - [ ] New alerts: _Go through them and either fix, dismiss och ignore. Add reasoning in items below._
  - [ ] Alerts fixed: _What?_
  - [ ] Alerts ignored / dismissed: _Why?_
  - [x] Passed
- **Snyk**: Security scanner
  - [ ] New alerts: _Go through them and either fix, dismiss och ignore. Add reasoning in items below._
  - [ ] Alerts fixed: _What?_
  - [ ] Alerts ignored / dismissed: _Why?_
  - [x] Passed

[DDS-1635]: https://scilifelab.atlassian.net/browse/DDS-1635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by rv0lt** [comment]
imagen

Should this be marked ?

**Comment by i-oden** [comment]
> imagen
> 
> Should this be marked ?

No only in the PRs from `dev` to `master`

**Comment by rv0lt** [comment]
> > imagen
> > Should this be marked ?
> 
> No only in the PRs from `dev` to `master`

Ah, yes. I got confussed with the other PR 🤦

**Comment by i-oden** [comment]
> > > imagen
> > > Should this be marked ?
> > 
> > 
> > No only in the PRs from `dev` to `master`
> 
> Ah, yes. I got confussed with the other PR 🤦

Understandable!

**Review by rv0lt — APPROVED** [review]
I dont' see anything weird

**Review by valyo — APPROVED** [review]

**Pull request merged**
