### PR TITLE
Change changelog to sprintlog and add "real" changelog for versions

### PR DESCRIPTION
**Pull request by i-oden**
## **1. This PR contains the following changes...**

In order to keep track of the versions, inform users in a simpler manner about new changes, and to simplify debugging, this changes the CHANGELOG.md to CHANGELOG.rst and includes the file in the documentation. This file contains information about the versions and what changes we have made to the CLI since the last release. Do not fill this in during PRs. 

The SPRINTLOG.md is now the previous CHANGELOG.md and should still be filled in -- this keeps track of what we have done during a specific sprint, _including_ changes to workflow, development setup, scannings, github actions etc, etc. 

## **2. The following additional changes are required for this to work**

To try this out:

1. Pull the code 
2. Go into the `docs` directory
3. Run `make clean html`
4. Run `open _build/html/index.html` 
5. There should be a new link on the left side of the page: "Changelog" - Click it
6. You should be directed to a new page with information about the changes in the last few versions: the changes possibly noticable by the users.

## **3. The PR fixes the following GitHub issue / Jira task**

- [ ] GitHub issue (link):
- [x] Jira task (ID, `DDS-xxxx`): DDS-1485
- [ ] The PR does not fix a specific GitHub issue or Jira task

## **4. What _type of change(s)_ does the PR contain?**

- [x] New feature
  - [ ] Breaking: _Please describe the reason for the break and how we can fix it._
  - [x] Non-breaking
- [ ] Bug fix
  - [ ] Breaking: _Please describe the reason for the break and how we can fix it._
  - [ ] Non-breaking
- [ ] Security Alert fix
- [x] Documentation
- [ ] Tests **(only)**
- [x] Workflow

### **Always**

- [Sprintlog](../SPRINTLOG.md)
  - [x] Added
  - [ ] Not needed (E.g. PR contains _only_ tests)
- Rebase / Update / Merge _from_ base branch (the branch from which the current is forked)
  - [ ] Done
  - [ ] Not needed
- Blocking PRs
  - [ ] Merged
  - [x] No blocking PRs
- PR to `master` branch
  - [ ] Yes: Go to the section [PR to master](#pr-to-master)
  - [x] No

## **6. Actions / Scans**

- **Black**: Python code formatter. Does not execute. Only tests.
  Run `black .` locally to execute formatting.
  - [x] Passed
- **Prettier**: General code formatter. Our use case: MD and yaml mainly.
  Run `npx prettier --write .` locally to execute formatting.
  - [x] Passed
- **Yamllint**: Linting of yaml files.
  - [x] Passed
- **Tests**: Pytest to verify that functionality works as expected.
  - [ ] New tests added
  - [x] No new tests
  - [x] Passed
- **TestPyPi**: Build CLI and publish to TestPyPi in order to verify before release.
  - [x] Passed
- **CodeQL**: Scan for security vulnerabilities, bugs, errors
  - [ ] New alerts: _Go through them and either fix, dismiss och ignore. Add reasoning in items below._
  - [ ] Alerts fixed: _What?_
  - [ ] Alerts ignored / dismissed: _Why?_
  - [x] Passed
- **Trivy**: Security scanner
  - [ ] New alerts: _Go through them and either fix, dismiss och ignore. Add reasoning in items below._
  - [ ] Alerts fixed: _What?_
  - [ ] Alerts ignored / dismissed: _Why?_
  - [x] Passed
- **Snyk**: Security scanner
  - [ ] New alerts: _Go through them and either fix, dismiss och ignore. Add reasoning in items below._
  - [ ] Alerts fixed: _What?_
  - [ ] Alerts ignored / dismissed: _Why?_
  - [x] Passed

### CODE REVIEW

**Comment by i-oden** [comment]
@valyo Could you have a look at this first thing today? If you agree that we should have this type of changelog, I'll also change it in `dds_web` during the day.

**Comment by valyo** [comment]
Would CHANGELOG.rst be updated manually on new releases?

**Review by valyo — APPROVED** [review]
Seems like a good idea, and for dds_web too.

**Comment by i-oden** [comment]
> Would CHANGELOG.rst be updated manually on new releases?

Yes. (Answered during meeting but adding here for future reference)

**Pull request merged**
