### PR TITLE
Set file permissions using icacls on Windows, no check

### PR DESCRIPTION
**Pull request by talavis**
Fix file permissions for token creation on Windows.
The internal check is skipped since it's not compatible with Windows.

To check whether it's correct:
```
icacls .dds_cli_token
```
Should only be one entry: `(your username): (R,W)`

Before submitting a PR to the `dev` branch:
- [x] Tests passing
- [X] Black formatting
- [X] Rebase/merge the `dev` branch
- [x] Note in the CHANGELOG

Additional checks before submitting a PR to the `master` branch:
- Change version in `setup.py` (?)

### CODE REVIEW

**Comment by inaod568** [comment]
@MatthiasZepper will test, preferably with the dev instance at https://dds-dev.dckube.scilifelab.se/
Pausing this for now until Linus is back - aside from changing the link in the cli code, where does the email etc end up?

**Comment by talavis** [comment]
The setup for Dev is almost identical to the production one. Emails from dsw.

**Comment by inaod568** [comment]
> The setup for Dev is almost identical to the production one. Emails from dsw.

Ok great. But currently it's the dev users right? And their emails don't exist. How do we get users and also use the 2fa and invite etc?

**Comment by inaod568** [comment]
@talavis What users are there in the dev setup?

**Comment by talavis** [comment]
> @talavis What users are there in the dev setup? 

Currently only a superadmin. I can add more on request.

**Comment by inaod568** [comment]
> > @talavis What users are there in the dev setup?
> 
> Currently only a superadmin. I can add more on request.

Ok! We can wait until after the retreat and then add me and @MatthiasZepper so that he can test your Windows PR without having to create the local setup.

**Review by inaod568 — APPROVED** [review]

**Review by MatthiasZepper — APPROVED** [review]
Tested in Windows 11 evaluation virtual machine. Works very well. Thanks!

**Pull request merged**
